name: ai-chat-frontend-dev

services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
